### ISSUE TITLE
Documentation : Check embedded hyperlinks in code Descriptions are valid

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Test_Toolkit#129]
As raised in  comment here:
https://github.com/BHoM/BHoM/pull/669#pullrequestreview-350035815

@IsakNaslundBh @FraserGreenroyd FYI

**Comment by awakeman** [comment]
Caveats here: It's probably a bad idea to rely on the existence of a specific network resource, especially if the link is to an external website that could be down or produce some unexpected error.

URLs in our own wiki or to places in our code can be validated in principle if the repo they link to is already cloned because we can programmatically map file paths to their eventual URLs. That said we *are* already relying on github and azure to be up and functioning properly so they are already holding that risk.

Just suggest we tread carefully adding additional variables that aren't in our control because false negatives introduce recalcitrance (although not as dangerous as false positives).

I'd say all in all there is probably less recalcitrance in checking than in not checking given that the alternative is dead links in the code.

Worth noting also that it'll only be a snapshot in time, it'll only show that the URL is good at time of the check, possibly worth checking for dead links across the entire source periodically so we can be notified.

Just some things to keep in mind.

**Comment by al-fisher** [comment]
In general - false negatives are not an issue here I don't think. 
In that I don't think we mind an automated process here throwing a rare false negative. This compliance check will naturally not be run across all code on every PR (we are only checking files changed) 
This will be a periodic check (daily? at end of sprint? at end of milestone?) - thus if false positive is caused by resource being unavailable - that will be evident / a specific check

We have talked about the frequency of when checks are run before. We should formalise categorisation for this now as we ramp up.
@FraserGreenroyd one for us to agree please in out next CI session. Thanks!  😄
