### ISSUE TITLE
Test_Toolkit: Compliance checks for required extension methods

### ISSUE THREAD

**Issue by kThorsager** [BHoM/Test_Toolkit#139]
#### Description:
In relation to migrating and giving `IElement` some structure, there should be compliance checks that ensures that the required extension methods exists for classes implementing `IElement`

Issue outlining which methods are required:
https://github.com/BHoM/BHoM_Engine/issues/1470

**Comment by FraserGreenroyd** [comment]
Linked to https://github.com/BHoM/Test_Toolkit/issues/91

**Comment by FraserGreenroyd** [comment]
@kThorsager can I get some more information on this. Where should, for compliance, the methods you link to be residing?

If I have an Environment oM object which implemented `IElement1D` for example, is the compliance rule that the associated engine (Environment_Engine in this case) as the methods you deem are required? Or can they be anywhere? Because if they can be anywhere... that causes some problems in terms of when we check.

If I'm being asked to produce the compliance rule, I would do it as above - that whichever oM has the object, its associated engine must implement those methods.

But if the rule needs to be something else then I'm going to need more to work on please.

Also, it would be good, as this is a new rule effectively, for us to document the wiki page which explains why this is necessary and why people need to follow it. Rules for rules sake are generally not good, but a rule which helps us in some way (consistency, guidance, reliability, etc.) are good, but we must be able to demonstrate to people why they need to be followed with some clear guidelines. We can use this issue to flesh that out in the first instance until we get something put up on the wiki,

Hope the above makes sense :smile:

**Comment by kThorsager** [comment]
Yes,

The `IElement`s interfaces works by being able to access some base methods from a point in the dependency chain where the specific methods for each implementation of `IElement` has not been defined yet.
That happens through using reflection to find the right method:
`Reflection.Compute.RunExtensionMethod(element0D, "Geometry")`
My understanding is that this method could be defined anywhere as long as it's among the methods available through the UI (ish?)
This also means that it will compile happily regardless.

I would however strongly suggest that we by compliance do force them to be defined in each oM's associated Engine
(will this cause problems for `IElement` in it self by being defined in Dimensional with Engine methods in Spatial, or will it be exempt by virtue of being a interface?)
A note is that this rule should be applied for oMs/Engines outside of the core BHoM as well

And I would say that this would be a helpful rule as it will be a continuation of the effort to ease the implementation of `IElement` and maintenance. As it is now the specific methods to implement are bundled up among the rest of the methods in Common (we will move them to Spatial and have them in a separate folder to ease finding them soon).
And as it runs through reflection, the only indication that you missed implementing a method is when you try to run a method which needs it in a script. Which could be difficult if you didn't find all the methods to implement in the first place.

Not sure where the wiki is tho, and would prefer to wait until the migration form Common to Spatial so that that's finalised. and can be referred to.

**Comment by FraserGreenroyd** [comment]
> I would however strongly suggest that we by compliance do force them to be defined in each oM's associated Engine

Good, we're in agreement on that then.

> (will this cause problems for `IElement` in it self by being defined in Dimensional with Engine methods in Spatial, or will it be exempt by virtue of being a interface?)

Yes I would say they will be because the interface methods themselves do not need the method implementations so that should be fine.

> Not sure where the wiki is tho, and would prefer to wait until the migration form Common to Spatial so that that's finalised. and can be referred to.

Wiki is here: https://github.com/BHoM/documentation/wiki

Code Compliance section is listed there. Documentation is sparse and growing as we roll out the compliance checks. The wiki can be written up as a very general rule anyway - I'm thinking the rule will be something like:

`Some interface classes have a required set of methods to be implemented in order to function correctly. However, due to the BHoM's philosophy of separating objects from engines, this is not enforced at the compilation level of the code, and is instead enforced through compliance. A list of interface methods which require suitable methods can be found below`

And then below would include all of the `IElement` stuff (the list you have on the linked issue https://github.com/BHoM/BHoM_Engine/issues/1470), and later, if we have more, we can add more. Thoughts?

**Comment by kThorsager** [comment]
Yes that does sound good, perhaps also a link to the API documentation if we could make it show up there? 

(is it suppose to be this spare?
![image](https://user-images.githubusercontent.com/53530468/75433143-6af1c100-5947-11ea-9149-9620971216f4.png)
)

**Comment by FraserGreenroyd** [comment]
Yep that's the space @kThorsager !

**Comment by kThorsager** [comment]
As I'm continuing to look at the `IElements` I'm noticing that the Geometry_oM does not have all their corresponding methods.
`ICurve` only has `GetGeometry`/`SetGeometry`
This however works as the only place that those methods get used begins by checking if it can use those methods and does nothing if it can't.
This does seem a lot like a design choice, which would mean that not all methods would be required, but if they have one of the optional methods they need all of them...

A more annoying and confusing rule and hopefully @pawelbaran can shed some light on things I should have asked him a lot sooner

**Comment by kThorsager** [comment]
Created the page detailing when and what to do to [follow compliance here](https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods)

And have confirmed that the optional methods detailed there are the only ones which are optional

And I'm kind of assuming that the optional requirement is a bother to get into a automatic compliance, so would not expect that (but would be pleasantly surprised)

Would you like it added to the sidebar now or when the compliance check exists @FraserGreenroyd

**Comment by FraserGreenroyd** [comment]
That looks good to me @kThorsager - I'm happy with that and happy for @awakeman or I to write the check for that based on that.

The optional requirements will not be able to be included because if it's optional it's optional, though we could look at doing a warning saying "do you need to implement these" but these are difficult to flag in the CI checks on PRs at this stage.

We can add it to the sidebar later @kThorsager - just remind me when we look to resolve this issue :smile:
