### ISSUE TITLE
ComplainceTest_Toolkit: Check that Quantity provided is correct type

### ISSUE THREAD

**Issue by IsakNaslundBh** [BHoM/Test_Toolkit#147]
#### Description:

After https://github.com/BHoM/BHoM_Engine/pull/1455 was merged, we can now provide Quantities as inputs.

Need compliance check to test that the type provided is a subclass to the attribute class `QuantityAttribute`. This will be true for both inputs and outputs

**Comment by FraserGreenroyd** [comment]
Following discussion with @IsakNaslundBh yesterday, this check is not quite so straight forward as originally thought.

A check has been added, which dynamically confirms that a `Quantity` property of an `InputAttribute` is of type `QuantityAttribute`, however, the test will never fail or return an error message. This is because the constructor for `InputAttribute` checks if the provided type of a `QuantityAttribute` and if it isn't, refuses to assign the type to the attribute.

This means that, at the time of running a compliance check on this, we would never fail the test.

Discussion with @IsakNaslundBh concluded that what might work is a combined static and dynamic check - whereby the static check will extract the quantity type, and then a dynamic check will match it to a compiled quantity.

However, on reflection, this may not work, in the instance where a quantity attribute does not exist in the Quantities_oM (e.g. is being prototyped up in another oM initially) and is inaccessible to Test_Toolkit at check time.

Current evaluation therefore is to add the check we have, as it will catch any failures or changes to the `InputAttribute` constructor later, and we may revisit how we do this check in the future, depending on how much of an issue it becomes.
