### ISSUE TITLE
CI Clone Test Toolkit to be isolated further?

### ISSUE THREAD

**Issue by al-fisher** [BHoM/Test_Toolkit#188]
There have been a couple of instances where the CI test fails as a result of the Clone Test Toolkit steps - rather than than the actual PR'd branches. Will be good to isolate further/version the Test Toolkit such that we do not get incompatible branch versions, giving I think false negative failures.

One to discuss @FraserGreenroyd 

Recent example:

#### Failing Commit to oM [here](https://github.com/BHoM/BHoM/pull/715/commits/6ea68c469bcbc7ca59e8cdb7fdd95a8e397a8295)

can see state here: 
![image](https://user-images.githubusercontent.com/15924573/76958865-5da97000-6910-11ea-94d7-349deee610c6.png)

#### Azure Job failing to build as part of Clone Test toolkit [here](https://dev.azure.com/BHoMBot/BHoM/_build/results?buildId=5785&view=logs&j=12f1170f-54f2-53f3-20dd-22fc7dff55f9&t=d1e88c09-dceb-53c1-5579-19c846f3526a)

**Comment by al-fisher** [comment]
@alelom FYI

**Comment by FraserGreenroyd** [comment]
@al-fisher I think BHoM did not receive the same updates to CI isolation that BHoM_Engine did when we were having difficulties there. I see the milestone is MVP of 3.2 so I presume there isn't anything holding up current work for close of this milestone?

**Comment by al-fisher** [comment]
> @al-fisher I think BHoM did not receive the same updates to CI isolation that BHoM_Engine did when we were having difficulties there. I see the milestone is MVP of 3.2 so I presume there isn't anything holding up current work for close of this milestone?

Yes - I wondered if it was a related issue. 

I do not think there is anything urgent - the specific issue was resolvable by just updating all dependant PRs to master.  But this ought to be unnecessary (assuming all the PRs are actually compatible amounts themselves)

Can pick up as part of 3.2 

Thanks @FraserGreenroyd

**Comment by al-fisher** [comment]
Had another odd one with AppVeyor too. Just noting here Fraser for us to do a general review in 3.2.
Ta
see https://github.com/BHoM/BHoM_UI/pull/222

**Comment by FraserGreenroyd** [comment]
So this has cropped up again this week, however, as we move towards utilising BHoMBot-CI more , I feel that this issue has been solved through isolating Test_Toolkit to nugets that work for the CI as opposed to conflicting between live builds. This means that the CI is version locked at run time, as opposed to being built every time it is needed, which is the current case with Azure.

As such, I feel this issue is being resolved through a natural evolution of CI operations, with our desired output for Azure to wind down and become a back up during the next couple of milestones. Thus I am going to close this issue on that basis, however if you feel this is the wrong answer then please do reopen :smile:
