### ISSUE TITLE
Incorrect Compliance fail for BH.Test.Test.Test_Adapter.CheckProjectFile for Structure_AdapterModules.dll

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/Test_Toolkit#268]
#### Description:

The `CheckProjectFile` returns a failure for `Structure_AdapterModules.dll`: 
![image](https://user-images.githubusercontent.com/30078587/88284897-1aa84080-cce6-11ea-9af0-078ce12272a4.png)

The expected file path is incorrect - as shown by the latest master build of the BHoM_Adapter:
![image](https://user-images.githubusercontent.com/30078587/88284961-390e3c00-cce6-11ea-9665-6315980d5e8a.png)

#### Steps to reproduce:

Run the `BH.Test.Test.Test_Adapter.CheckProjectFile` on any structural adapter (as they all reference the `Structure_AdaptersModule.dll` in their Adapter,

#### Expected behaviour:

No compliance fail for `Structure_AdapterModules.dll`

#### Test file(s):

See the two following PRs:
https://github.com/BHoM/Lusas_Toolkit/pull/272
https://github.com/BHoM/MidasCivil_Toolkit/pull/212

**Comment by FraserGreenroyd** [comment]
This should now have been fixed following some refactoring of how this check is performed as we migrate towards a new way of doing the checks.

I have not seen this issue be reproduced recently, but accept that I may not have been testing it on the right PRs.

However, on the basis that it ought to have been fixed by the refactor, I am closing this issue. @peterjamesnugent please reopen if you encounter the issue again and we can reinvestigate :smile:
