### ISSUE TITLE
Allow for testing a method that returns nothing

### ISSUE THREAD

**Issue by rolyhudson** [BHoM/Test_Toolkit#318]
#### Description:
This would be useful for situations like in the Geometry_Engine intersection methods where I think we need and should be able to test for cases when the method is expected to return nothing. 

For example no intersection between two lines could return nothing:
![Screenshot 2021-01-21 152709](https://user-images.githubusercontent.com/6618854/105372073-27f2a900-5bfd-11eb-8884-fd55aba556c3.jpg)
Plug those inputs to the unit test and check it:
![Screenshot 2021-01-21 152900](https://user-images.githubusercontent.com/6618854/105372566-9fc0d380-5bfd-11eb-9837-4766d20f585c.jpg)

**Comment by FraserGreenroyd** [comment]
I would agree with this @rolyhudson - no answer is the right answer in a large number of cases, particularly in the Geometry Space.

That said though, those do look like two different types of `LineIntersection` methods, because one has `angleTolerance` and the top one doesn't, so were you definitely testing the right component when that example was made?

**Comment by rolyhudson** [comment]
@FraserGreenroyd thanks for noting the difference on the method and the UT. 
I just checked the correct pair and although the method does not return nothing the error is the same.
![Screenshot 2021-01-21 154136](https://user-images.githubusercontent.com/6618854/105374233-612c1880-5bff-11eb-8a20-f5645309d70a.jpg)
